### ISSUE TITLE
Halo Reach Injection Issue 

### ISSUE THREAD

**Issue by Lehvak** [XboxChaos/Assembly#147]
Issue occurred when trying to inject a grunt bipd tag.

Error: 
System.ArgumentNullException: Value cannot be null.
Parameter name: resource is null
   at Blamite.Injection.TagContainerInjector.InjectResource(ExtractedResourceInfo resource, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixResourceReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixTagReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixTagReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectDataBlock(DataBlock block, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixBlockReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)
   at Blamite.Injection.TagContainerInjector.FixTagReferences(DataBlock block, IWriter buffer, IStream stream)
   at Blamite.Injection.TagContainerInjector.WriteDataBlock(DataBlock block, SegmentPointer location, IStream stream)
   at Blamite.Injection.TagContainerInjector.InjectTag(ExtractedTag tag, IStream stream)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.btnImport_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Lord-Zedd** [comment]
Been a year and a half, so going to close this.
