### ISSUE TITLE
"System.ArgumentOutOfRangeException: Index was out of range" on map load

### ISSUE THREAD

**Issue by imFlipp** [XboxChaos/Assembly#174]
Any time i try to load a map i get the following error:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass32_1.<InitalizeMap>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap(String tagsLocation, String stringsLocation, String filesLocation)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.initalLoadBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by imFlipp** [comment]
Figured out the problem, my files were corrupted.... stupid me.

**Comment by ChadSki** [comment]
Why did you close the issue? Is this no longer a problem?

Which maps were you trying to load?

**Comment by imFlipp** [comment]
I solved the problem the file i was using was corrupted so I just got a newer copy and it worked correctly. I was loading a halo 3 map (but i think the copy i had was from the Halo Online) so theres no problem anymore :)

**Comment by ThunderWaffle** [comment]
Glad you figured it out.
