### ISSUE TITLE
Halo 3 Beta, trying to open any of the maps when:

### ISSUE THREAD

**Issue by TheVengefulVadam** [XboxChaos/Assembly#180]
System.ArgumentException: The structure is missing the required "offset masks" field.
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_1.<InitalizeMap>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.initalLoadBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by Lord-Zedd** [comment]
Halo 3 Beta support was broken a while back. You will need to compile the WIP "halo3beta" branch in order to open/save them again.
