### ISSUE TITLE
I'm not sure what happened but this still happens even after a fresh install of assembly.

### ISSUE THREAD

**Issue by Dead-Inside** [XboxChaos/Assembly#186]
### System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass32_1.<InitalizeMap>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap(String tagsLocation, String stringsLocation, String filesLocation)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.initalLoadBackgroundWorker_DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
------------------------------------------------------------------------------------------
This is the code it spits out when attempting to modify anything.

**Comment by 0xdeafcafe** [comment]
Closing due to age.
