### ISSUE TITLE
Access to the path 

### ISSUE THREAD

**Issue by iSupersniper** [XboxChaos/Assembly#197]
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\Magic\AppData\Local\Temp\update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at Assembly.Helpers.VariousFunctions.EmptyUpdaterLocations()
   at Assembly.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Downloaded the assembly version in releases, ran as admin. it prompted an update.  However I don't believe the updater ran as admin.

**Comment by ChadSki** [comment]
The exception is thrown from Assembly.exe, so if you launched it as admin it should have permission to delete the file.

Maybe update.exe was running at the time, and that's why it wasn't allowed to delete the file?

**Comment by 0xdeafcafe** [comment]
Closing due to age.
