### ISSUE TITLE
Assembly "crashes" while trying to extract audio from Halo 3 intro map

### ISSUE THREAD

**Issue by chris-hawley** [XboxChaos/Assembly#208]
The crash log is long so it'll be at the end

steps to reproduce:
1. have assembly 2016.11.04.19.07.00-master (most recent release I could find)
2. open assembly
3. go to your halo 3 game directory
4. open maps
5. open 005_intro.map
6. click tags
7. expand "cine"
8. click 010jungle_intro01
9. select meta editor
10. scroll down the cinematic scenes
11. select chief_discovery
12. hit the -> button
13. (from new window) scroll down to background sounds
14. select 010la_music_1_3
15. hit the -> button
16. on the new tab, look along the bottom of the screen and click "sound editor"
17. hit "extract complete raw sound" 
18. pick a save location
19. hit save
20. observe crash

It doesn't actually crash but rather gives what would normally be sean in visual studio's terminal on a crash. the first time I ran this, it said "file not found" but now it's saying unimplemented function

Here is the complete log it gave me

System.NotImplementedException: The method or operation is not implemented.
   at Assembly.Metro.Controls.PageTemplates.Games.Components.Editors.SoundEditor.ConvertToAudioFile(ICollection`1 data, String path)
   at Assembly.Metro.Controls.PageTemplates.Games.Components.Editors.SoundEditor.btnExtractRawSound_Click(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Lord-Zedd** [comment]
That particular exception is happening because only stereo/mono channels are supported, but that tag uses surround sound. I'd recommend Adjutant but it appears that doesn't support surround sound either.

However, there are no current plans to work on/fix the sound editor at this time.

**Comment by chris-hawley** [comment]
Can you change it so it supports extracting the raw audio? Adjutant can do that but without the header information.
