### ISSUE TITLE
impossible to save anything

### ISSUE THREAD

**Issue by C4PTRAMPAGE** [XboxChaos/Assembly#270]
this happens on every tag in every map i open, from what i can tell the error below says the map file is read only, that is not the case and this never happened until i made the mistake of checking for updates, i think the version i was using last was something like 2020.XX.XX.19.XX.XX-dev and the current version is 2020.02.04.20.00.00-dev i'm in the process of working on a huge mod for mcc reach needless to say i need assembly working asap so is there any way i can roll back the update while this gets fixed? if there is no way to roll back an update then i'm requesting that feature be added.

error message:

System.Exception: An UnauthorizedAccessException has occurred.

Chances are the map/content file you just tried to modify is set to readonly.
Verify the readonly status of your file and try again before reporting this.

 ---> System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at Assembly.Metro.Controls.PageTemplates.Games.Components.MetaEditor.UpdateMeta(SaveType type, Boolean onlyUpdateChanged, Boolean showActionDialog)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   --- End of inner exception stack trace ---

**Comment by Arttumiro** [comment]
are you playing the map when you are saving?

If you are, dont. Exit to main menu first lol.

**Comment by C4PTRAMPAGE** [comment]
once again someone on github who doesn't know how to read! 

"this happens on every tag in every map i open"
obviously i cant have every map loaded at once

"this never happened until i made the mistake of checking for updates"
as you can see i said everything was fine until i updated

and no i never edit the map the game is running only a copy of it

**Comment by C4PTRAMPAGE** [comment]
it seem to me like everyone here thinks the problem is on my end so i'm going to put an end to argument https://www.youtube.com/watch?v=KdLiTrnVR8s

**Comment by Lord-Zedd** [comment]
You can switch to the stable update branch to receive the previous build now. As far as your issue, can you try running Assembly as admin? The readonly message is custom and not a guaranteed explanation.

**Comment by C4PTRAMPAGE** [comment]
something i should have put in that post with the video link, i may have gotten a bit upset during the making of that, which often happens when someone tells me i'm wrong when i'm clearly not.

**Comment by C4PTRAMPAGE** [comment]
and I've tried that already running it as admin doesn't change anything it gives the same error, i just checked again now to confirm

**Comment by C4PTRAMPAGE** [comment]
...and setting it to the stable branch doesn't change anything either wonderful

**Comment by ThunderWaffle** [comment]
I'd check the owning directory as well as the file itself for read-only bits.  Typically its going to be one of 5 things wrong:

- Caller of the save routine doesn't have permission (unlikely if you run as admin)
- File in use by another process (unlikely if the game is not open and another assembly is not open)
- You're writing to a directory (this is impossible given you opened the map)
- File or directory is read-only (by process of elimination this might it)
- Antivirus may be blocking write.

**Comment by C4PTRAMPAGE** [comment]
if you watched the video you'd know its assembly's fault because i used an older version of it and it worked fine! 

LISTEN UP BECAUSE THIS IS THE LAST TIME I'M GOING OVER IT: I HAVE CHECKED EVERYTHING, THE PROBLEM HERE IS NOT ON MY END!!!!!!

**Comment by C4PTRAMPAGE** [comment]
@ThunderWaffle its impossible 1 - 4 are the cause (watch the video in my post above) and i just checked 5 now it makes no difference if i shut off my antivirus, if you watched the video you'd know its assembly's fault because i used an older version and the new version of it and the old one worked fine!

EVERYONE LISTEN UP BECAUSE THIS IS THE LAST TIME I'M GOING OVER IT: I HAVE CHECKED EVERYTHING, THE PROBLEM HERE IS NOT ON MY END!!!!!!

**Comment by ThunderWaffle** [comment]
Screaming in caps lock is not going to make anyone want to help you more.

If you want to roll back, grab this version of assembly.  Its the previous December 28th experimental release.

http://api.xboxchaos.com/downloads/dev_dec_28_2019.zip

**Comment by C4PTRAMPAGE** [comment]
@ThunderWaffle do you understand that its NOT just about fixing the issue FOR ME its about fixing the problem period, statistically, if one person is experiencing a bug with some software than at least several others are too, while yes, me posting this bug report is entirely motivated by me wanting it to work for me i still see the big picture here and if others cant that on them not me.
in any case this discussion is off topic and serves no purpose.

unless anyone ...preferably someone else... has something USEFUL to say, don't say anything.

**Comment by ThunderWaffle** [comment]
K I tried being nice.
