### ISSUE TITLE
System.ArgumentException: Invalid cache file header magic

### ISSUE THREAD

**Issue by rlewkowicz** [XboxChaos/Assembly#275]
```
System.ArgumentException: Invalid cache file header magic
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_0.<InitalizeMap>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```
I get this error opening a halo cea map with halo mcc

**Comment by Lord-Zedd** [comment]
CEA is currently not supported by assembly. there is a fork that is being working on to be merged in the future https://github.com/Dragonflare921/Assembly/tree/dev_first_gen

**Comment by rlewkowicz** [comment]
As a heads up, you also need: 

https://github.com/Dragonflare921/MCCCEADeflate/releases
