### ISSUE TITLE
Can't edit tags of Halo CE Anniversary

### ISSUE THREAD

**Issue by retardedloozer** [XboxChaos/Assembly#282]
**Describe the bug**
When I try to open a .map file of Halo CE Anniversary using Assembly, I get an error

**To Reproduce**
Tried to open d40.map in Assembly and got this error

https://i.imgur.com/05PvrNk.png

**PC (please complete the following information):**
I'm running Windows 10 Professional 64 bit. CPU is AMD Athlon X4 760k, GPU is AMD R9 270.

**Additional Context**

I should probably provide the full text of the error....

System.ArgumentException: Invalid cache file header magic
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_0.<InitalizeMap>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by ThunderWaffle** [comment]
For CEA you need to check out the CEA fork:

https://github.com/Dragonflare921/Assembly

**Comment by retardedloozer** [comment]
Its it's giving the same bug?
