### ISSUE TITLE
Invalid cache file header magic

### ISSUE THREAD

**Issue by Rusoski** [XboxChaos/Assembly#288]
This happens while trying to open a .map file

I just launched Assembly++ for the first time and followed the straight forward instructions, but can't even open a .map file

System.ArgumentException: Invalid cache file header magic
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_0.<InitalizeMap>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by 0xdeafcafe** [comment]
Assembly++ isn't the real Assembly, was forked from here by some fucking idiots. Download the real and supported version from here: https://github.com/XboxChaos/Assembly/releases/tag/downloader.

It should work after that. If you're opening a Halo 2 Classic map from MCC PC, then you'll need to decompress the map first with the decompressor build into Assembly in the Tools tab 👍

**Comment by Rusoski** [comment]
Thank you so much, I was very confused, because I downloaded it from Gamebanana first, then from Nexus, but no one of those worked.

I will try it as soon as I get home! Thank you again! :D

**Comment by Rusoski** [comment]
Bro, I am also getting issues with the one you have provided

System.ArgumentException: Invalid cache file header magic
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_0.<InitalizeMap>b__3()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by 0xdeafcafe** [comment]
I think you make have to update to the "experimental" branch, the option is in the update window. You can get to it from the menu bar
