### ISSUE TITLE
Opening Scripts in H2Vista or H2MCC Error

### ISSUE THREAD

**Issue by theHostileNegotiator** [XboxChaos/Assembly#318]
An attempt to open scripts in Halo 2 maps presents this error:

System.ArgumentException: Script value types can only have a size of 1, 2 or 4 bytes. The size 0 is invalid.
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GetValue(ScriptExpression expression, ScriptValueType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateGroup(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateGroup(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateGroup(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateGroup(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.GenerateGroup(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.HandleExpression(IndentedTextWriter output, ScriptExpression expression, Boolean newLine)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.FollowRootIndex(IndentedTextWriter output, DatumIndex root, Boolean newLine, BranchType type)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.WriteScripts(IndentedTextWriter output, Boolean showInfo)
   at Blamite.Blam.Scripting.BlamScriptDecompiler.DecompileAll(String sourceFile, Boolean showInfo, Boolean writeHeader)
   at Assembly.Metro.Controls.PageTemplates.Games.Components.Editors.ScriptEditor.DecompileScnrScripts()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Assembly.Metro.Controls.PageTemplates.Games.Components.Editors.ScriptEditor.<EditorLoadedAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Lord-Zedd** [comment]
Should be fixed now.
