### ISSUE TITLE
Unauthorized Access Exception?

### ISSUE THREAD

**Issue by stingray818** [XboxChaos/Assembly#339]
**Describe the bug** (Got this after the latest update. Updated on 7/23/21 Even uninstalled and reinstalled everything multiple times)
System.Exception: An UnauthorizedAccessException has occurred.

Chances are you either need Admin privileges or the map/content file you just tried to modify is set to readonly.
Run Assembly as Administrator and verify the readonly status of your file before reporting this.

 ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\Futur\AppData\Local\Temp\update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Assembly.Helpers.VariousFunctions.EmptyUpdaterLocations()
   at Assembly.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   --- End of inner exception stack trace ---

**Comment by A267-dev** [comment]
Change the Directory of your Repo to where Elevated Permissions are not required.
