### ISSUE TITLE
Halo 2 Map Loading Exception - build 2024.02.14.15.24.44-dev

### ISSUE THREAD

**Issue by ToffeeSurprise** [XboxChaos/Assembly#366]
**Describe the bug**
Attempting to load a stock MCC Halo 2 map in the latest public build 2024.02.14.15.24.44-dev results in the following error:

"Invalid index table header magic. This map could be compressed, try the Compressor in the Tools menu before reporting."

Full output:

"System.ArgumentException: Invalid index table header magic. This map could be compressed, try the Compressor in the Tools menu before reporting.
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.<>c__DisplayClass26_1.<InitalizeMap>b__4()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Assembly.Metro.Controls.PageTemplates.Games.HaloMap.InitalizeMap()
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)"

**To Reproduce**
1. Attempt to open a Halo 2 map.
2. Assembly will fail to open the map and raises the above exception.

**Expected behavior**
The map should open in Assembly.

**Screenshots**

**PC (please complete the following information):**

**Additional context**
Attempted with multiple Halo 2 maps that are all stock. This only impacts Halo 2 maps, all other games in the collection have the map files open as expected.

**Comment by Lord-Zedd** [comment]
Halo 2 maps in MCC are compressed. You can decompress them by selecting Tools>Map Compressor. The exception mentions compression but actually for H2 MCC I could make it more clear since the state of compression is a flag in the header.
